# Generated by Django 4.0.2 on 2022-09-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='propertyData',
            fields=[
                ('dateFound', models.DateField(auto_now_add=True)),
                ('propertyID', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('roadName', models.CharField(max_length=100)),
                ('jerseyArea', models.CharField(max_length=100)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('parking', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
