# Generated by Django 4.0.2 on 2022-09-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydata',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
