# Generated by Django 4.0.2 on 2022-09-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_propertydata_bathrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydata',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertydata',
            name='dateFound',
            field=models.DateField(),
        ),
    ]
