# Generated by Django 4.0.2 on 2022-09-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_propertydata_bedrooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Parish', models.CharField(max_length=100)),
                ('Average', models.IntegerField()),
            ],
        ),
    ]
